const bcrypt = require('bcryptjs');

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Clear existing entries
  await knex('users').del();

  // Hash passwords
  const saltRounds = 12;
  const hashedPassword = await bcrypt.hash('password123', saltRounds);
  const adminPassword = await bcrypt.hash('admin123', saltRounds);
  const organizerPassword = await bcrypt.hash('organizer123', saltRounds);
  const venuePassword = await bcrypt.hash('venue123', saltRounds);

  // Insert seed users
  await knex('users').insert([
    {
      email: 'admin@ShashaPass.com',
      password_hash: adminPassword,
      first_name: 'System',
      last_name: 'Administrator',
      phone: '+263-123-456-789',
      role: 'admin',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '123 Admin Street',
      city: 'Harare',
      state: 'Harare',
      country: 'Zimbabwe',
      postal_code: '0001',
      id_number: 'ADMIN001',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'customer@example.com',
      password_hash: hashedPassword,
      first_name: 'John',
      last_name: 'Customer',
      phone: '+263-77-123-4567',
      role: 'customer',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '456 Customer Avenue',
      city: 'Bulawayo',
      state: 'Bulawayo',
      country: 'Zimbabwe',
      postal_code: '0026',
      id_number: 'CUST001',
      date_of_birth: '1990-05-15',
      gender: 'male',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'organizer@example.com',
      password_hash: organizerPassword,
      first_name: 'Sarah',
      last_name: 'Organizer',
      phone: '+263-78-234-5678',
      role: 'organizer',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '789 Event Plaza',
      city: 'Harare',
      state: 'Harare',
      country: 'Zimbabwe',
      postal_code: '0002',
      id_number: 'ORG001',
      date_of_birth: '1985-03-20',
      gender: 'female',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'venue@example.com',
      password_hash: venuePassword,
      first_name: 'Michael',
      last_name: 'Venue',
      phone: '+263-71-345-6789',
      role: 'venue_manager',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '321 Venue Boulevard',
      city: 'Mutare',
      state: 'Manicaland',
      country: 'Zimbabwe',
      postal_code: '7000',
      id_number: 'VEN001',
      date_of_birth: '1978-11-10',
      gender: 'male',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'jane.customer@ShashaPass.com',
      password_hash: hashedPassword,
      first_name: 'Jane',
      last_name: 'Smith',
      phone: '+263-73-456-7890',
      role: 'customer',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '567 Residential Road',
      city: 'Gweru',
      state: 'Midlands',
      country: 'Zimbabwe',
      postal_code: '1620',
      id_number: 'CUST002',
      date_of_birth: '1992-08-25',
      gender: 'female',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'events@harareconventions.com',
      password_hash: organizerPassword,
      first_name: 'David',
      last_name: 'Events',
      phone: '+263-24-700-000',
      role: 'organizer',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '1 Convention Center Drive',
      city: 'Harare',
      state: 'Harare',
      country: 'Zimbabwe',
      postal_code: '0001',
      id_number: 'ORG002',
      date_of_birth: '1980-12-05',
      gender: 'male',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'manager@bulawayostadium.co.zw',
      password_hash: venuePassword,
      first_name: 'Grace',
      last_name: 'Stadium',
      phone: '+263-29-123-456',
      role: 'venue_manager',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '1 Stadium Drive',
      city: 'Bulawayo',
      state: 'Bulawayo',
      country: 'Zimbabwe',
      postal_code: '0026',
      id_number: 'VEN002',
      date_of_birth: '1975-06-30',
      gender: 'female',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'customer2@example.com',
      password_hash: hashedPassword,
      first_name: 'Peter',
      last_name: 'Johnson',
      phone: '+263-77-987-6543',
      role: 'customer',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '890 Residential Way',
      city: 'Masvingo',
      state: 'Masvingo',
      country: 'Zimbabwe',
      postal_code: '2630',
      id_number: 'CUST003',
      date_of_birth: '1988-01-12',
      gender: 'male',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'music@zimfestivals.co.zw',
      password_hash: organizerPassword,
      first_name: 'Tendai',
      last_name: 'Music',
      phone: '+263-77-555-0123',
      role: 'organizer',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: '45 Music Avenue',
      city: 'Harare',
      state: 'Harare',
      country: 'Zimbabwe',
      postal_code: '0003',
      id_number: 'ORG003',
      date_of_birth: '1983-09-18',
      gender: 'male',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      email: 'sports@nationalstadium.zw',
      password_hash: venuePassword,
      first_name: 'Blessing',
      last_name: 'Sports',
      phone: '+263-24-123-789',
      role: 'venue_manager',
      is_active: true,
      is_verified: true,
      email_verified: true,
      phone_verified: true,
      address: 'National Sports Stadium',
      city: 'Harare',
      state: 'Harare',
      country: 'Zimbabwe',
      postal_code: '0001',
      id_number: 'VEN003',
      date_of_birth: '1970-04-22',
      gender: 'female',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    }
  ]);

  console.log('✅ Users seeded successfully');
};
