/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Clear existing entries
  await knex('events').del();

  // Get venue and organizer IDs
  const harareConference = await knex('venues').where('name', 'Harare International Conference Centre').first();
  const bulawayoStadium = await knex('venues').where('name', 'Barbourfields Stadium').first();
  const nationalStadium = await knex('venues').where('name', 'National Sports Stadium').first();
  const theatrePark = await knex('venues').where('name', 'The Theatre In The Park').first();
  const rainbowTowers = await knex('venues').where('name', 'Rainbow Towers Conference Centre').first();

  const eventOrganizer = await knex('users').where('email', 'events@harareconventions.com').first();
  const musicOrganizer = await knex('users').where('email', 'music@zimfestivals.co.zw').first();

  // Insert seed events
  await knex('events').insert([
    {
      title: 'Tech Innovation Summit 2026',
      description: 'Annual technology conference featuring Zimbabwe\'s leading tech innovators, entrepreneurs, and industry leaders. Topics include AI, blockchain, fintech, and digital transformation.',
      short_description: 'Zimbabwe\'s premier technology conference and networking event.',
      event_type: 'conference',
      category: 'business',
      venue_id: harareConference?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-02-15T09:00:00Z'),
      end_date: new Date('2026-02-16T17:00:00Z'),
      base_price: 150.00,
      currency: 'USD',
      total_capacity: 800,
      available_tickets: 800,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
      tags: JSON.stringify(['technology', 'innovation', 'networking', 'business']),
      terms_and_conditions: 'Standard conference terms apply. Refund policy: Full refund 30 days prior, 50% refund 14 days prior, no refunds within 7 days.',
      refund_policy: 'Flexible refund policy with processing fees waived for early cancellations.',
      is_featured: true,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-01-01T00:00:00Z'),
      sales_end_date: new Date('2026-02-14T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Highlanders FC vs Dynamos FC',
      description: 'Premier Soccer League derby match between two of Zimbabwe\'s most historic football clubs. Experience the passion, skill, and excitement of local football at its finest.',
      short_description: 'Historic Zimbabwe Premier Soccer League derby match.',
      event_type: 'sports',
      category: 'sports_soccer',
      venue_id: nationalStadium?.id,
      organizer_id: null, // League organized
      start_date: new Date('2026-03-10T15:00:00Z'),
      end_date: new Date('2026-03-10T17:00:00Z'),
      base_price: 25.00,
      currency: 'USD',
      total_capacity: 35000,
      available_tickets: 35000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
      tags: JSON.stringify(['football', 'soccer', 'sports', 'premier league', 'derby']),
      terms_and_conditions: 'Match tickets are non-refundable. Children under 12 half price. No outside food or drink allowed.',
      refund_policy: 'No refunds on match tickets except in case of postponement.',
      is_featured: true,
      requires_approval: false,
      min_age: 0,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-02-01T00:00:00Z'),
      sales_end_date: new Date('2026-03-10T14:00:00Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Zimbabwe Music Awards 2024 - Live Stream',
      description: 'Watch the prestigious Zimbabwe Music Awards live from the comfort of your home! Featuring performances by top Zimbabwean artists across all genres including Afrobeat, Hip-Hop, Gospel, and Traditional music.',
      short_description: 'Live streaming of Zimbabwe\'s biggest music awards ceremony.',
      event_type: 'concert',
      category: 'music',
      venue_id: theatrePark?.id,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2024-04-20T19:00:00Z'),
      end_date: new Date('2024-04-20T23:00:00Z'),
      base_price: 15.00,
      currency: 'USD',
      total_capacity: 1200, // Venue capacity, but streaming allows unlimited viewers
      available_tickets: 10000, // Streaming tickets
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
      tags: JSON.stringify(['music', 'awards', 'live stream', 'zimbabwe music', 'performance']),
      terms_and_conditions: 'Streaming access valid for 24 hours after event. HD quality guaranteed. Technical support available.',
      refund_policy: 'Full refund available up to 24 hours before event start.',
      is_featured: true,
      requires_approval: false,
      min_age: 0,
      has_seating: false, // Streaming event
      // Streaming-specific fields
      is_streaming_event: true,
      stream_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Placeholder
      stream_key: 'STREAM_KEY_2024_AWARDS',
      stream_provider: 'youtube',
      stream_embed_code: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allowfullscreen></iframe>',
      stream_start_time: new Date('2024-04-20T19:00:00Z'),
      stream_end_time: new Date('2024-04-20T23:00:00Z'),
      streaming_price: 15.00,
      allow_replay: true,
      replay_available_until: new Date('2024-04-27T23:59:59Z'), // 1 week replay
      stream_description: 'Professional live streaming with multiple camera angles, interviews, and behind-the-scenes content.',
      published_at: new Date(),
      sales_start_date: new Date('2026-03-01T00:00:00Z'),
      sales_end_date: new Date('2026-04-20T18:00:00Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Business Leadership Conference',
      description: 'Annual business conference bringing together CEOs, entrepreneurs, and business leaders from across Zimbabwe and the region. Featuring keynote speakers, workshops, and networking opportunities.',
      short_description: 'Premier business networking and leadership conference.',
      event_type: 'conference',
      category: 'business',
      venue_id: rainbowTowers?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-05-08T08:30:00Z'),
      end_date: new Date('2026-05-09T17:30:00Z'),
      base_price: 200.00,
      currency: 'USD',
      total_capacity: 400,
      available_tickets: 400,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800',
      tags: JSON.stringify(['business', 'leadership', 'networking', 'entrepreneurship', 'conference']),
      terms_and_conditions: 'Professional attire required. Meals included. Parking validation provided.',
      refund_policy: 'Full refund 21 days prior, 75% refund 7 days prior, no refunds within 48 hours.',
      is_featured: false,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-03-01T00:00:00Z'),
      sales_end_date: new Date('2026-05-07T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'ZIFA National Team vs South Africa - Pay Per View',
      description: 'Watch Zimbabwe\'s national football team take on South Africa in this crucial international friendly. Live streaming with expert commentary and analysis.',
      short_description: 'International friendly match - Zimbabwe vs South Africa with live streaming.',
      event_type: 'sports',
      category: 'sports_soccer',
      venue_id: nationalStadium?.id,
      organizer_id: null,
      start_date: new Date('2026-06-15T16:00:00Z'),
      end_date: new Date('2026-06-15T18:00:00Z'),
      base_price: 10.00,
      currency: 'USD',
      total_capacity: 60000,
      available_tickets: 50000, // Streaming tickets
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
      tags: JSON.stringify(['football', 'international', 'live stream', 'pay per view', 'zimbabwe']),
      terms_and_conditions: 'Streaming access includes multiple camera angles and post-match highlights.',
      refund_policy: 'No refunds for streaming purchases.',
      is_featured: true,
      requires_approval: false,
      min_age: 0,
      has_seating: false,
      // Streaming fields
      is_streaming_event: true,
      stream_url: 'https://www.youtube.com/watch?v=STREAM_KEY_ZIFA',
      stream_key: 'ZIFA_VS_RSA_2024',
      stream_provider: 'youtube',
      stream_embed_code: '<iframe width="560" height="315" src="https://www.youtube.com/embed/VIDEO_ID" frameborder="0" allowfullscreen></iframe>',
      stream_start_time: new Date('2026-06-15T16:00:00Z'),
      stream_end_time: new Date('2026-06-15T18:00:00Z'),
      streaming_price: 10.00,
      allow_replay: true,
      replay_available_until: new Date('2026-06-22T23:59:59Z'),
      stream_description: 'Professional broadcast with multiple camera angles, expert commentary, and instant replays.',
      published_at: new Date(),
      sales_start_date: new Date('2026-05-01T00:00:00Z'),
      sales_end_date: new Date('2026-06-15T15:30:00Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Harare International Arts Festival',
      description: 'Celebrating Zimbabwean culture through music, dance, theater, and visual arts. Featuring performances by local and international artists across multiple venues.',
      short_description: 'Multi-day cultural festival celebrating Zimbabwean arts and heritage.',
      event_type: 'festival',
      category: 'arts',
      venue_id: theatrePark?.id,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2026-07-12T10:00:00Z'),
      end_date: new Date('2026-07-14T22:00:00Z'),
      base_price: 50.00,
      currency: 'USD',
      total_capacity: 1200,
      available_tickets: 1200,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
      tags: JSON.stringify(['arts', 'culture', 'festival', 'music', 'dance', 'theater', 'zimbabwe']),
      terms_and_conditions: '3-day festival pass. Access to all performances and exhibitions. Camping available on-site.',
      refund_policy: '50% refund available up to 14 days before festival start.',
      is_featured: true,
      requires_approval: false,
      min_age: 0,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-04-01T00:00:00Z'),
      sales_end_date: new Date('2026-07-11T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Corporate Team Building Workshop',
      description: 'Interactive team building workshop designed for corporate groups. Includes icebreakers, leadership exercises, and collaborative activities in a scenic location.',
      short_description: 'Professional team building workshop for corporate groups.',
      event_type: 'conference',
      category: 'business',
      venue_id: null, // Off-site location
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-08-05T09:00:00Z'),
      end_date: new Date('2026-08-05T17:00:00Z'),
      base_price: 75.00,
      currency: 'USD',
      total_capacity: 50,
      available_tickets: 50,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800',
      tags: JSON.stringify(['corporate', 'team building', 'workshop', 'leadership', 'training']),
      terms_and_conditions: 'Minimum group size of 10 required. Catering and materials included.',
      refund_policy: 'Full refund with 48 hours notice, 50% refund within 24 hours.',
      is_featured: false,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Victoria Falls Travel Expo',
      description: 'Travel and tourism exhibition showcasing Zimbabwe\'s tourism offerings, adventure activities, and accommodation options. Perfect for planning your next vacation.',
      short_description: 'Travel exhibition featuring Zimbabwe\'s tourism attractions and services.',
      event_type: 'exhibition',
      category: 'travel_bus',
      venue_id: null, // Victoria Falls venue
      organizer_id: null,
      start_date: new Date('2024-09-20T10:00:00Z'),
      end_date: new Date('2024-09-22T18:00:00Z'),
      base_price: 20.00,
      currency: 'USD',
      total_capacity: 2000,
      available_tickets: 2000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      tags: JSON.stringify(['travel', 'tourism', 'exhibition', 'victoria falls', 'zimbabwe']),
      terms_and_conditions: '3-day exhibition pass. Free shuttle service from hotels.',
      refund_policy: 'Full refund available up to exhibition start.',
      is_featured: false,
      requires_approval: false,
      min_age: 0,
      has_seating: false,
      published_at: new Date(),
      sales_start_date: new Date('2026-07-01T00:00:00Z'),
      sales_end_date: new Date('2026-09-19T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Zimbabwe Fashion Week 2026',
      description: 'Showcase of the latest in African fashion trends featuring local designers. Two days of runway shows, exhibitions, and fashion talks.',
      short_description: 'Premier fashion showcase featuring local African designers.',
      event_type: 'festival',
      category: 'arts',
      venue_id: null,
      organizer_id: null,
      start_date: new Date('2026-10-05T11:00:00Z'),
      end_date: new Date('2026-10-06T20:00:00Z'),
      base_price: 35.00,
      currency: 'USD',
      total_capacity: 800,
      available_tickets: 800,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      tags: JSON.stringify(['fashion', 'designers', 'runway', 'zimbabwe', 'african fashion']),
      terms_and_conditions: '2-day pass includes all runway shows and exhibitions. VIP packages available.',
      refund_policy: '75% refund up to 7 days before event.',
      is_featured: true,
      requires_approval: false,
      min_age: 16,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-07-15T00:00:00Z'),
      sales_end_date: new Date('2026-10-04T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Harare Comedy Night - Stand-up Special',
      description: 'Evening of laughter featuring Zimbabwe\'s funniest comedians. A night of stand-up comedy showcasing local talent and international acts.',
      short_description: 'Stand-up comedy show featuring local and international comedians.',
      event_type: 'concert',
      category: 'entertainment',
      venue_id: null,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2026-10-12T19:30:00Z'),
      end_date: new Date('2026-10-12T22:00:00Z'),
      base_price: 30.00,
      currency: 'USD',
      total_capacity: 500,
      available_tickets: 500,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
      tags: JSON.stringify(['comedy', 'entertainment', 'stand-up', 'zimbabwe', 'humor']),
      terms_and_conditions: 'Adults 18+. Comedy may contain explicit content. No outside beverages allowed.',
      refund_policy: 'Full refund up to 24 hours before event.',
      is_featured: true,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-08-01T00:00:00Z'),
      sales_end_date: new Date('2026-10-11T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Harare Marathon 2026',
      description: 'Annual running event for fitness enthusiasts of all levels. Half marathon and full marathon categories. Join thousands of participants.',
      short_description: 'Annual running marathon event for all fitness levels.',
      event_type: 'sports',
      category: 'sports_other',
      venue_id: null,
      organizer_id: null,
      start_date: new Date('2026-10-20T06:00:00Z'),
      end_date: new Date('2026-10-20T12:00:00Z'),
      base_price: 45.00,
      currency: 'USD',
      total_capacity: 5000,
      available_tickets: 5000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
      tags: JSON.stringify(['sports', 'marathon', 'running', 'fitness', 'athletics']),
      terms_and_conditions: 'Must be 16 or older. Bring your own water bottle. Medical personnel on site.',
      refund_policy: 'No refunds after race day, transfers allowed up to 48 hours before.',
      is_featured: true,
      requires_approval: false,
      min_age: 16,
      has_seating: false,
      published_at: new Date(),
      sales_start_date: new Date('2026-08-01T00:00:00Z'),
      sales_end_date: new Date('2026-10-19T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Digital Marketing Masterclass',
      description: 'Intensive workshop on modern digital marketing strategies including SEO, social media, content marketing, and analytics.',
      short_description: 'Professional masterclass in digital marketing and online strategy.',
      event_type: 'conference',
      category: 'business',
      venue_id: rainbowTowers?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-11-08T09:00:00Z'),
      end_date: new Date('2026-11-08T17:00:00Z'),
      base_price: 120.00,
      currency: 'USD',
      total_capacity: 100,
      available_tickets: 100,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
      tags: JSON.stringify(['marketing', 'digital', 'training', 'business', 'seo']),
      terms_and_conditions: 'Certificate of completion provided. Lunch and materials included. Limited to 100 participants.',
      refund_policy: 'Full refund up to 3 days before event.',
      is_featured: false,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-09-01T00:00:00Z'),
      sales_end_date: new Date('2026-11-07T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Bulawayo Music Carnival',
      description: 'Multi-day music festival in Bulawayo featuring local and regional artists. Live performances, DJ sets, and cultural entertainment.',
      short_description: 'Three-day music carnival in Bulawayo with multiple performing artists.',
      event_type: 'festival',
      category: 'music',
      venue_id: bulawayoStadium?.id,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2026-11-15T12:00:00Z'),
      end_date: new Date('2026-11-17T23:00:00Z'),
      base_price: 60.00,
      currency: 'USD',
      total_capacity: 10000,
      available_tickets: 10000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1514890547357-a9db7a4513c3?w=800',
      tags: JSON.stringify(['music', 'festival', 'bulawayo', 'carnival', 'entertainment']),
      terms_and_conditions: '3-day pass. Camping on-site available. Food and beverages available for purchase.',
      refund_policy: 'Refunds available up to 7 days before event.',
      is_featured: true,
      requires_approval: false,
      min_age: 0,
      has_seating: false,
      published_at: new Date(),
      sales_start_date: new Date('2026-09-01T00:00:00Z'),
      sales_end_date: new Date('2026-11-14T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Tech Startup Pitch Competition',
      description: 'Annual competition for tech startups to pitch their ideas to investors and venture capitalists. Win funding and mentorship opportunities.',
      short_description: 'Startup pitch competition with investor opportunities and funding prizes.',
      event_type: 'conference',
      category: 'business',
      venue_id: harareConference?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-12-01T14:00:00Z'),
      end_date: new Date('2026-12-01T18:00:00Z'),
      base_price: 25.00,
      currency: 'USD',
      total_capacity: 300,
      available_tickets: 300,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
      tags: JSON.stringify(['startup', 'pitch', 'technology', 'investment', 'entrepreneurship']),
      terms_and_conditions: 'Startups can register to pitch. Spectators welcome. Networking opportunities with investors.',
      refund_policy: 'Full refund up to 5 days before event.',
      is_featured: true,
      requires_approval: false,
      min_age: 0,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-10-01T00:00:00Z'),
      sales_end_date: new Date('2026-11-30T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'New Year Gala Dinner & Dance',
      description: 'Elegant evening celebration to ring in the new year with fine dining, live entertainment, and dancing until midnight.',
      short_description: 'Premium New Year\'s Eve gala celebration with fine dining and entertainment.',
      event_type: 'festival',
      category: 'entertainment',
      venue_id: rainbowTowers?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-12-31T19:00:00Z'),
      end_date: new Date('2027-01-01T03:00:00Z'),
      base_price: 200.00,
      currency: 'USD',
      total_capacity: 200,
      available_tickets: 200,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1519671482677-0d8a57d21c58?w=800',
      tags: JSON.stringify(['new year', 'gala', 'celebration', 'fine dining', 'entertainment']),
      terms_and_conditions: 'Formal dress required. Black tie recommended. Limited seating. Premium bar available.',
      refund_policy: 'No refunds within 14 days of event.',
      is_featured: true,
      requires_approval: false,
      min_age: 21,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-11-01T00:00:00Z'),
      sales_end_date: new Date('2026-12-28T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    }
  ]);

  console.log('✅ Events seeded successfully');
};
