/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Clear existing entries
  await knex('events').del();

  // Get venue and organizer IDs
  const kicc = await knex('venues').where('name', 'Kenyatta International Convention Centre').first();
  const kasarani = await knex('venues').where('name', 'Kasarani Stadium (Moi International Sports Centre)').first();
  const nyayo = await knex('venues').where('name', 'Nyayo National Stadium').first();
  const nationalTheatre = await knex('venues').where('name', 'Kenya National Theatre').first();
  const saritCentre = await knex('venues').where('name', 'Sarit Centre Expo Centre').first();
  const mombasaBeach = await knex('venues').where('name', 'Mombasa Beach Arena').first();

  const eventOrganizer = await knex('users').where('email', 'events@kenyaconventions.co.ke').first();
  const musicOrganizer = await knex('users').where('email', 'music@kenyafestivals.co.ke').first();

  // Insert Kenyan seed events
  await knex('events').insert([
    {
      title: 'Nairobi Tech Summit 2026',
      description: 'Annual technology conference featuring Kenya\'s leading tech innovators, entrepreneurs, and industry leaders. Topics include AI, blockchain, fintech, mobile money, and digital transformation.',
      short_description: 'Kenya\'s premier technology conference and networking event.',
      event_type: 'conference',
      category: 'business',
      venue_id: kicc?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-03-15T09:00:00Z'),
      end_date: new Date('2026-03-16T17:00:00Z'),
      base_price: 8500.00,
      currency: 'KES',
      total_capacity: 1200,
      available_tickets: 1200,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
      tags: JSON.stringify(['technology', 'innovation', 'networking', 'business', 'fintech']),
      terms_and_conditions: 'Standard conference terms apply. Refund policy: Full refund 30 days prior, 50% refund 14 days prior, no refunds within 7 days.',
      refund_policy: 'Flexible refund policy with processing fees waived for early cancellations.',
      is_featured: true,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-01-01T00:00:00Z'),
      sales_end_date: new Date('2026-03-14T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Safari Sound Festival',
      description: 'Kenya\'s biggest music festival featuring top local and international artists across multiple genres including Afrobeats, Gengetone, Benga, and contemporary music.',
      short_description: 'Experience the best of Kenyan and African music in one electrifying festival.',
      event_type: 'festival',
      category: 'music',
      venue_id: mombasaBeach?.id,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2026-04-20T16:00:00Z'),
      end_date: new Date('2026-04-21T23:00:00Z'),
      base_price: 2500.00,
      currency: 'KES',
      total_capacity: 5000,
      available_tickets: 5000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
      tags: JSON.stringify(['music', 'festival', 'afrobeats', 'gengetone', 'live_performance']),
      terms_and_conditions: 'Festival terms apply. No refunds within 7 days of event. Weather policy applies for outdoor events.',
      refund_policy: 'Full refund 14 days prior, 50% refund 7 days prior, no refunds within 7 days.',
      is_featured: true,
      requires_approval: false,
      min_age: 16,
      has_seating: false,
      published_at: new Date(),
      sales_start_date: new Date('2026-01-15T00:00:00Z'),
      sales_end_date: new Date('2026-04-19T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Kenya Premier League: Gor Mahia vs AFC Leopards',
      description: 'The biggest football derby in Kenya featuring the two most successful clubs in Kenyan football history. A must-see match for any football fan.',
      short_description: "Kenya's most intense football rivalry at the national stadium.",
      event_type: 'sports',
      category: 'football',
      venue_id: nyayo?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-02-28T15:00:00Z'),
      end_date: new Date('2026-02-28T18:00:00Z'),
      base_price: 500.00,
      currency: 'KES',
      total_capacity: 25000,
      available_tickets: 25000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800',
      tags: JSON.stringify(['football', 'sports', 'kpl', 'derby', 'gor_mahia', 'afc_leopards']),
      terms_and_conditions: 'Standard stadium terms apply. No weapons, alcohol, or outside food allowed.',
      refund_policy: 'Full refund 48 hours before match, no refunds within 48 hours.',
      is_featured: false,
      requires_approval: false,
      min_age: 5,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-01-01T00:00:00Z'),
      sales_end_date: new Date('2026-02-27T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Kenya Fashion Week',
      description: 'Showcasing the best of Kenyan fashion design with runway shows, designer exhibitions, and networking opportunities for fashion professionals.',
      short_description: 'Celebrate Kenya\'s vibrant fashion industry and emerging designers.',
      event_type: 'fashion_show',
      category: 'fashion',
      venue_id: kicc?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-05-10T18:00:00Z'),
      end_date: new Date('2026-05-12T21:00:00Z'),
      base_price: 3500.00,
      currency: 'KES',
      total_capacity: 2000,
      available_tickets: 2000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
      tags: JSON.stringify(['fashion', 'design', 'runway', 'kenyan_designers', 'style']),
      terms_and_conditions: 'Fashion week terms apply. Professional photography restrictions may apply.',
      refund_policy: 'Full refund 7 days prior, no refunds within 7 days.',
      is_featured: true,
      requires_approval: false,
      min_age: 16,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-02-01T00:00:00Z'),
      sales_end_date: new Date('2026-05-09T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'M-Pesa Mobile Money Conference',
      description: 'Exploring the future of mobile money and digital payments in Kenya and across Africa. Features industry leaders from M-Pesa, banks, and fintech startups.',
      short_description: 'The premier event for mobile money and digital payment professionals.',
      event_type: 'conference',
      category: 'business',
      venue_id: saritCentre?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-06-05T09:00:00Z'),
      end_date: new Date('2026-06-05T17:00:00Z'),
      base_price: 4500.00,
      currency: 'KES',
      total_capacity: 500,
      available_tickets: 500,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1563986768494-47dee0e271e3?w=800',
      tags: JSON.stringify(['mobile_money', 'fintech', 'mpesa', 'digital_payments', 'banking']),
      terms_and_conditions: 'Conference terms apply. Networking sessions included.',
      refund_policy: 'Full refund 14 days prior, 50% refund 7 days prior, no refunds within 7 days.',
      is_featured: false,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-03-01T00:00:00Z'),
      sales_end_date: new Date('2026-06-04T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Kenya International Comedy Festival',
      description: 'Featuring top comedians from Kenya and across Africa, including stand-up, improv, and sketch comedy performances.',
      short_description: 'Laugh out loud with Africa\'s best comedians in Nairobi.',
      event_type: 'comedy',
      category: 'entertainment',
      venue_id: nationalTheatre?.id,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2026-07-15T19:00:00Z'),
      end_date: new Date('2026-07-17T22:00:00Z'),
      base_price: 1500.00,
      currency: 'KES',
      total_capacity: 600,
      available_tickets: 600,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
      tags: JSON.stringify(['comedy', 'stand_up', 'entertainment', 'african_comedy', 'live_performance']),
      terms_and_conditions: 'Comedy show terms apply. Age restrictions may apply for certain performances.',
      refund_policy: 'Full refund 7 days prior, no refunds within 7 days.',
      is_featured: false,
      requires_approval: false,
      min_age: 18,
      has_seating: true,
      published_at: new Date(),
      sales_start_date: new Date('2026-04-01T00:00:00Z'),
      sales_end_date: new Date('2026-07-14T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Nairobi Marathon 2026',
      description: 'Kenya\'s premier running event featuring full marathon, half marathon, 10km, and 5km races through the streets of Nairobi.',
      short_description: 'Run with champions in Kenya\'s capital city marathon.',
      event_type: 'sports',
      category: 'running',
      venue_id: nyayo?.id,
      organizer_id: eventOrganizer?.id,
      start_date: new Date('2026-10-26T06:00:00Z'),
      end_date: new Date('2026-10-26T14:00:00Z'),
      base_price: 2000.00,
      currency: 'KES',
      total_capacity: 20000,
      available_tickets: 20000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
      tags: JSON.stringify(['marathon', 'running', 'sports', 'fitness', 'nairobi', 'athletics']),
      terms_and_conditions: 'Marathon terms apply. Medical certificate required for full marathon participants.',
      refund_policy: 'Full refund 30 days prior, 50% refund 14 days prior, no refunds within 14 days.',
      is_featured: true,
      requires_approval: false,
      min_age: 16,
      has_seating: false,
      published_at: new Date(),
      sales_start_date: new Date('2026-05-01T00:00:00Z'),
      sales_end_date: new Date('2026-10-25T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    },
    {
      title: 'Kenyan Food & Wine Festival',
      description: 'Celebrate Kenya\'s diverse culinary scene with traditional dishes, modern fusion cuisine, local wines, and international flavors.',
      short_description: 'Taste the best of Kenyan cuisine and beverages at this food lover\'s paradise.',
      event_type: 'festival',
      category: 'food',
      venue_id: mombasaBeach?.id,
      organizer_id: musicOrganizer?.id,
      start_date: new Date('2026-08-10T12:00:00Z'),
      end_date: new Date('2026-08-11T22:00:00Z'),
      base_price: 1800.00,
      currency: 'KES',
      total_capacity: 3000,
      available_tickets: 3000,
      sold_tickets: 0,
      status: 'published',
      event_image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      tags: JSON.stringify(['food', 'wine', 'kenyan_cuisine', 'festival', 'culinary', 'tasting']),
      terms_and_conditions: 'Food festival terms apply. Allergen information available at venue.',
      refund_policy: 'Full refund 7 days prior, no refunds within 7 days.',
      is_featured: false,
      requires_approval: false,
      min_age: 18,
      has_seating: false,
      published_at: new Date(),
      sales_start_date: new Date('2026-05-15T00:00:00Z'),
      sales_end_date: new Date('2026-08-09T23:59:59Z'),
      created_at: knex.fn.now(),
      updated_at: knex.fn.now()
    }
  ]);
};
